### PR TITLE
made Content-Type and Accept header for POST requests configurable

### PR DESCRIPTION
**Pull request by AxelBehrens**
Hi,
I needed  to have the Content-Type to be something other than the default application/x-www-form-urlencoded so I made that configurable and while I was at it, did the same with Accept.

Cheers,
Axel

### CODE REVIEW

**Comment by shekyan** [comment]
Sorry, i am travelling and will take a look on Saturday. 
Thank you!

**Comment by shekyan** [comment]
@AxelBehrens , capital letter options were used for options without arguments, so could you please change `-A` and `-C` to be something else. For example, `-f` looks like a good option for `Content-type`, just as in curl. And for `Accept`, may be `-m` is an ok option, or whatever you think is better. 
Otherwise, LGTM.

**Comment by shekyan** [comment]
Closed through #27

**Comment by AxelBehrens** [comment]
Hi,
I'm really sorry for being ignorant regarding this PR, normally that's not my style ;-). 

Glad you find it useful!

Cheers,
Axel

**Pull request closed without merging**
